// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

class FfiBufUri {
  final Uri field0;

  const FfiBufUri({
    required this.field0,
  });

  String address() => core.instance.api.crateApiBitcoinUriFfiBufUriAddress(
        that: this,
      );

  BigInt? amountSats() =>
      core.instance.api.crateApiBitcoinUriFfiBufUriAmountSats(
        that: this,
      );

  String asString() => core.instance.api.crateApiBitcoinUriFfiBufUriAsString(
        that: this,
      );

  String? label() => core.instance.api.crateApiBitcoinUriFfiBufUriLabel(
        that: this,
      );

  String? message() => core.instance.api.crateApiBitcoinUriFfiBufUriMessage(
        that: this,
      );

  static FfiBufUri parse({required String uri}) =>
      core.instance.api.crateApiBitcoinUriFfiBufUriParse(uri: uri);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiBufUri &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}
